### ISSUE TITLE
Release update notification

### ISSUE THREAD

**Issue by intika** [Intika-UC/uc-arch-binaries#1]
@ian-moone 
[ungoogled-chromium_70.0.3538.110-1_linux.tar.xz](https://github.com/intika/uc-arch-binaries/releases/download/70.0.3538.110-1/ungoogled-chromium_70.0.3538.110-1_linux.tar.xz)

**Comment by ghost** [comment]
Superb!!

**Comment by intika** [comment]
new release for ya :) https://github.com/intika/uc-arch-binaries/releases 
it also fix this https://github.com/Eloston/ungoogled-chromium/issues/556
